classdef RFtiming < handle
    %Block Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        
        parent_adwin    % parent Adwin class
        
    end
    
    properties % GUI structures
        
        rfg    % RF timing GUI
        
        frg    % RF frequency GUI
        
        beg    % RF behaviour GUI
        
    end
    
    properties (SetObservable = true) % listened properties
        
        timing_formula        % formula that defines the timing of the event
        
        freq_formula          % formula that defines the frequency of the RF
        
        timing
        
        frequency
        
        behaviour
        
        behaviour_function
        
    end
    
    properties % RF properties
        
        rf_timing_nbr % Number of the RF_timing
        
    end
    
    properties % listeners list
        
        lst_behaviour
        
        lst_behaviour_function
        
        lst_timing_formula
        
        lst_freq_formula
        
        lst_timing
        
        lst_frequency
        
    end
    
    methods
        
        function obj = RFtiming ()
            
            obj = obj@handle;
            
            obj.lst_timing_formula = addlistener(obj,'timing_formula','PostSet',@obj.postset_timing_formula);
            
            obj.lst_freq_formula = addlistener(obj,'freq_formula','PostSet',@obj.postset_freq_formula);
            
            obj.lst_behaviour = addlistener(obj,'behaviour','PostSet',@obj.postset_behaviour);
            
            obj.lst_behaviour_function = addlistener(obj,'behaviour_function','PostSet',@obj.postset_behaviour);
            
            obj.lst_timing = addlistener(obj,'timing','PreSet',@obj.preset_timing);
            
            obj.lst_frequency = addlistener(obj,'frequency','PreSet',@obj.preset_frequency);

        end
        
        function rf_timing_btd_fcn(obj,~,~)
            
            if ~isempty(obj.rfg)&&ishandle(obj.rfg.h)
                
                set(obj.rfg,'Visible','off');
                set(obj.rfg,'Visible','on');
                
            else
                
                obj.rfg.h = figure(...
                    'Name'                ,'RF timing' ...
                    ,'NumberTitle'        ,'off' ...
                    ,'Position'           ,[200 200 200 200] ...
                    ,'MenuBar'            ,'none'...
                    ,'CloseRequestFcn'    ,@obj.rfg_closereq ...
                    );
                
                obj.rfg.hsp1 = uipanel(...
                    'Parent'              ,obj.rfg.h ...
                    ,'Title'              ,'Timing' ...
                    ,'TitlePosition'      ,'lefttop' ...
                    ,'BackgroundColor'    ,Adwin.Default_parameters.Panel_BackgroundColor ...
                    ,'ForegroundColor'    ,Adwin.Default_parameters.Panel_ForegroundColor ...
                    ,'HighlightColor'     ,Adwin.Default_parameters.Panel_HighlightColor ...
                    ,'ShadowColor'        ,Adwin.Default_parameters.Panel_ShadowColor ...
                    ,'FontName'           ,Adwin.Default_parameters.Panel_FontName ...
                    ,'FontSize'           ,Adwin.Default_parameters.Panel_FontSize ...
                    ,'FontUnits'          ,Adwin.Default_parameters.Panel_FontUnits ...
                    ,'FontWeight'         ,Adwin.Default_parameters.Panel_FontWeight ...
                    ,'SelectionHighlight' ,Adwin.Default_parameters.Panel_SelectionHighlight ...
                    ,'Units'              ,Adwin.Default_parameters.Panel_Units ...
                    ,'Position'           ,[0.015 0.015 0.97 0.97] ...
                    );
                
                obj.rfg.txt1 = uicontrol(...
                    'Parent'                ,obj.rfg.hsp1 ...
                    ,'Style'                ,'text' ...
                    ,'String'               ,'Timing formula' ...
                    ,'FontName'             ,Adwin.Default_parameters.Text_FontName ...
                    ,'FontSize'             ,Adwin.Default_parameters.Text_FontSize ...
                    ,'FontUnits'            ,Adwin.Default_parameters.Text_FontUnits ...
                    ,'FontWeight'           ,Adwin.Default_parameters.Text_FontWeight ...
                    ,'HorizontalAlignment'  ,Adwin.Default_parameters.Text_HorizontalAlignment ...
                    ,'Units'                ,Adwin.Default_parameters.Text_Units ...
                    ,'Position'             ,[0.05 0.8 0.40 0.15] ...
                    );
                
                obj.rfg.edt = uicontrol(...
                    'Parent'                ,obj.rfg.hsp1 ...
                    ,'Style'                ,'edit' ...
                    ,'String'               ,obj.timing_formula ...
                    ,'Units'                ,Adwin.Default_parameters.Edit_Units ...
                    ,'Position'             ,[0.55 0.8 0.40 0.15] ...
                    ,'Callback'             ,@obj.rfg_edt_clb ...
                    );
                
                obj.rfg.txt2 = uicontrol(...
                    'Parent'                ,obj.rfg.hsp1 ...
                    ,'Style'                ,'text' ...
                    ,'String'               ,'Timing' ...
                    ,'FontName'             ,Adwin.Default_parameters.Text_FontName ...
                    ,'FontSize'             ,Adwin.Default_parameters.Text_FontSize ...
                    ,'FontUnits'            ,Adwin.Default_parameters.Text_FontUnits ...
                    ,'FontWeight'           ,Adwin.Default_parameters.Text_FontWeight ...
                    ,'HorizontalAlignment'  ,Adwin.Default_parameters.Text_HorizontalAlignment ...
                    ,'Units'                ,Adwin.Default_parameters.Text_Units ...
                    ,'Position'             ,[0.05 0.6 0.40 0.15] ...
                    );
                
                obj.rfg.txt3 = uicontrol(...
                    'Parent'                ,obj.rfg.hsp1 ...
                    ,'Style'                ,'text' ...
                    ,'String'               ,num2str(obj.timing) ...
                    ,'FontName'             ,Adwin.Default_parameters.Text_FontName ...
                    ,'FontSize'             ,Adwin.Default_parameters.Text_FontSize ...
                    ,'FontUnits'            ,Adwin.Default_parameters.Text_FontUnits ...
                    ,'FontWeight'           ,'normal' ...
                    ,'HorizontalAlignment'  ,Adwin.Default_parameters.Text_HorizontalAlignment ...
                    ,'Units'                ,Adwin.Default_parameters.Text_Units ...
                    ,'Position'             ,[0.55 0.6 0.40 0.15] ...
                    );
                
                % update timing
                
                obj.postset_timing_formula;
                
            end
            
        end
        
        function rf_frq_btd_fcn(obj,~,~)
            
            if ~isempty(obj.frg)&&ishandle(obj.frg.h)
                
                set(obj.frg,'Visible','off');
                set(obj.frg,'Visible','on');
                
            else
                
                obj.frg.h = figure(...
                    'Name'                ,'RF frequency' ...
                    ,'NumberTitle'        ,'off' ...
                    ,'Position'           ,[200 200 200 200] ...
                    ,'MenuBar'            ,'none'...
                    ,'CloseRequestFcn'    ,@obj.frg_closereq ...
                    );
                
                obj.frg.hsp1 = uipanel(...
                    'Parent'              ,obj.frg.h ...
                    ,'Title'              ,'Frequency' ...
                    ,'TitlePosition'      ,'lefttop' ...
                    ,'BackgroundColor'    ,Adwin.Default_parameters.Panel_BackgroundColor ...
                    ,'ForegroundColor'    ,Adwin.Default_parameters.Panel_ForegroundColor ...
                    ,'HighlightColor'     ,Adwin.Default_parameters.Panel_HighlightColor ...
                    ,'ShadowColor'        ,Adwin.Default_parameters.Panel_ShadowColor ...
                    ,'FontName'           ,Adwin.Default_parameters.Panel_FontName ...
                    ,'FontSize'           ,Adwin.Default_parameters.Panel_FontSize ...
                    ,'FontUnits'          ,Adwin.Default_parameters.Panel_FontUnits ...
                    ,'FontWeight'         ,Adwin.Default_parameters.Panel_FontWeight ...
                    ,'SelectionHighlight' ,Adwin.Default_parameters.Panel_SelectionHighlight ...
                    ,'Units'              ,Adwin.Default_parameters.Panel_Units ...
                    ,'Position'           ,[0.015 0.015 0.97 0.97] ...
                    );
                
                obj.frg.txt1 = uicontrol(...
                    'Parent'                ,obj.frg.hsp1 ...
                    ,'Style'                ,'text' ...
                    ,'String'               ,'Frequency formula' ...
                    ,'FontName'             ,Adwin.Default_parameters.Text_FontName ...
                    ,'FontSize'             ,Adwin.Default_parameters.Text_FontSize ...
                    ,'FontUnits'            ,Adwin.Default_parameters.Text_FontUnits ...
                    ,'FontWeight'           ,Adwin.Default_parameters.Text_FontWeight ...
                    ,'HorizontalAlignment'  ,Adwin.Default_parameters.Text_HorizontalAlignment ...
                    ,'Units'                ,Adwin.Default_parameters.Text_Units ...
                    ,'Position'             ,[0.05 0.8 0.40 0.15] ...
                    );
                
                obj.frg.edt = uicontrol(...
                    'Parent'                ,obj.frg.hsp1 ...
                    ,'Style'                ,'edit' ...
                    ,'String'               ,obj.freq_formula ...
                    ,'Units'                ,Adwin.Default_parameters.Edit_Units ...
                    ,'Position'             ,[0.55 0.8 0.40 0.15] ...
                    ,'Callback'             ,@obj.frg_edt_clb ...
                    );
                
                obj.frg.txt2 = uicontrol(...
                    'Parent'                ,obj.frg.hsp1 ...
                    ,'Style'                ,'text' ...
                    ,'String'               ,'Frequency' ...
                    ,'FontName'             ,Adwin.Default_parameters.Text_FontName ...
                    ,'FontSize'             ,Adwin.Default_parameters.Text_FontSize ...
                    ,'FontUnits'            ,Adwin.Default_parameters.Text_FontUnits ...
                    ,'FontWeight'           ,Adwin.Default_parameters.Text_FontWeight ...
                    ,'HorizontalAlignment'  ,Adwin.Default_parameters.Text_HorizontalAlignment ...
                    ,'Units'                ,Adwin.Default_parameters.Text_Units ...
                    ,'Position'             ,[0.05 0.6 0.40 0.15] ...
                    );
                
                obj.frg.txt3 = uicontrol(...
                    'Parent'                ,obj.frg.hsp1 ...
                    ,'Style'                ,'text' ...
                    ,'String'               ,num2str(obj.frequency) ...
                    ,'FontName'             ,Adwin.Default_parameters.Text_FontName ...
                    ,'FontSize'             ,Adwin.Default_parameters.Text_FontSize ...
                    ,'FontUnits'            ,Adwin.Default_parameters.Text_FontUnits ...
                    ,'FontWeight'           ,'normal' ...
                    ,'HorizontalAlignment'  ,Adwin.Default_parameters.Text_HorizontalAlignment ...
                    ,'Units'                ,Adwin.Default_parameters.Text_Units ...
                    ,'Position'             ,[0.55 0.6 0.40 0.15] ...
                    );
                
                % update timing
                
                obj.postset_freq_formula;
                
            end
                
        end
        
        function rf_beh_clb(obj,~,~)
            
            if ~isempty(obj.beg)&&ishandle(obj.beg.h)
                
                set(obj.beg.h,...
                    'Visible'               ,'on' ...
                    );
                
                switch obj.behaviour
                    
                    case 'C'
                        
                        set(obj.beg.rbt_1,'Value',1)
                        
                    case 'R'
                        
                        set(obj.beg.rbt_2,'Value',1)
                        
                    case 'S'
                        
                        set(obj.beg.rbt_3,'Value',1)
                        set(obj.beg.edt1,'String',obj.behaviour_function)
                        
                        
                end
                
                
            else
                
                
                obj.beg.h = figure(...
                    'Name'                ,'Behaviour' ...
                    ,'NumberTitle'        ,'off' ...
                    ,'Position'           ,[200 200 290 200] ... ,'MenuBar'            ,'none'...
                    ,'CloseRequestFcn'    ,@obj.beg_closereq ...
                    );
                
                obj.beg.hsp1 = uipanel(...
                    'Parent'              ,obj.beg.h ...
                    ,'Title'              ,'Behaviour' ...
                    ,'TitlePosition'      ,'lefttop' ...
                    ,'BackgroundColor'    ,Adwin.Default_parameters.Panel_BackgroundColor ...
                    ,'ForegroundColor'    ,Adwin.Default_parameters.Panel_ForegroundColor ...
                    ,'HighlightColor'     ,Adwin.Default_parameters.Panel_HighlightColor ...
                    ,'ShadowColor'        ,Adwin.Default_parameters.Panel_ShadowColor ...
                    ,'FontName'           ,Adwin.Default_parameters.Panel_FontName ...
                    ,'FontSize'           ,Adwin.Default_parameters.Panel_FontSize ...
                    ,'FontUnits'          ,Adwin.Default_parameters.Panel_FontUnits ...
                    ,'FontWeight'         ,Adwin.Default_parameters.Panel_FontWeight ...
                    ,'SelectionHighlight' ,Adwin.Default_parameters.Panel_SelectionHighlight ...
                    ,'Units'              ,Adwin.Default_parameters.Panel_Units ...
                    ,'Position'           ,[0.015 0.015 0.97 0.97] ...
                    );
                
                obj.beg.uibutgp = uibuttongroup(...
                    'Parent'              ,obj.beg.hsp1 ...
                    ,'Units'              ,'normalized' ...
                    ,'Position'           ,[0.015 0.35 0.97 0.62] ...
                    ,'SelectionChangeFcn' ,@obj.beg_uibutgp_sel_chg_fcn ...
                    );
                
                obj.beg.rbt_1 = uicontrol(...
                    'Parent'                ,obj.beg.uibutgp ...
                    ,'Style'                ,'radiobutton' ...
                    ,'String'               ,'Constant' ...
                    ,'FontName'             ,Adwin.Default_parameters.Radiobutton_FontName ...
                    ,'FontSize'             ,Adwin.Default_parameters.Radiobutton_FontSize ...
                    ,'FontUnits'            ,Adwin.Default_parameters.Radiobutton_FontUnits ...
                    ,'FontWeight'           ,Adwin.Default_parameters.Radiobutton_FontWeight ...
                    ,'Units'                ,Adwin.Default_parameters.Radiobutton_Units ...
                    ,'Position'             ,[0.015 0.75 0.3 0.2] ...
                    );
                
                obj.beg.rbt_2 = uicontrol(...
                    'Parent'                ,obj.beg.uibutgp ...
                    ,'Style'                ,'radiobutton' ...
                    ,'String'               ,'Ramp' ...
                    ,'FontName'             ,Adwin.Default_parameters.Radiobutton_FontName ...
                    ,'FontSize'             ,Adwin.Default_parameters.Radiobutton_FontSize ...
                    ,'FontUnits'            ,Adwin.Default_parameters.Radiobutton_FontUnits ...
                    ,'FontWeight'           ,Adwin.Default_parameters.Radiobutton_FontWeight ...
                    ,'Units'                ,Adwin.Default_parameters.Radiobutton_Units ...
                    ,'Position'             ,[0.015 0.4 0.3 0.2] ...
                    );
                
                obj.beg.rbt_3 = uicontrol(...
                    'Parent'                ,obj.beg.uibutgp ...
                    ,'Style'                ,'radiobutton' ...
                    ,'String'               ,'Custom' ...
                    ,'FontName'             ,Adwin.Default_parameters.Radiobutton_FontName ...
                    ,'FontSize'             ,Adwin.Default_parameters.Radiobutton_FontSize ...
                    ,'FontUnits'            ,Adwin.Default_parameters.Radiobutton_FontUnits ...
                    ,'FontWeight'           ,Adwin.Default_parameters.Radiobutton_FontWeight ...
                    ,'Units'                ,Adwin.Default_parameters.Radiobutton_Units ...
                    ,'Position'             ,[0.015 0.05 0.3 0.2] ...
                    );
                
                obj.beg.txt1 = uicontrol(...
                    'Parent'                ,obj.beg.hsp1 ...
                    ,'Style'                ,'text' ...
                    ,'String'               ,'Custom function name' ...
                    ,'FontName'             ,Adwin.Default_parameters.Text_FontName ...
                    ,'FontSize'             ,Adwin.Default_parameters.Text_FontSize ...
                    ,'FontUnits'            ,Adwin.Default_parameters.Text_FontUnits ...
                    ,'FontWeight'           ,Adwin.Default_parameters.Text_FontWeight ...
                    ,'HorizontalAlignment'  ,Adwin.Default_parameters.Text_HorizontalAlignment ...
                    ,'Units'                ,Adwin.Default_parameters.Text_Units ...
                    ,'Position'             ,[0.05 0.12 0.50 0.1] ...
                    ,'Enable'               ,'off' ...
                    );
                
                obj.beg.edt1 = uicontrol(...
                    'Parent'                ,obj.beg.hsp1 ...
                    ,'Style'                ,'edit' ...
                    ,'String'               ,'' ...
                    ,'Units'                ,Adwin.Default_parameters.Edit_Units ...
                    ,'Position'             ,[0.6 0.1 0.35 0.15] ...
                    ,'Enable'               ,'off' ...
                    ,'Callback'             ,@obj.beg_edt1_clb ...
                    );
                
                switch obj.behaviour
                    
                    case 'C'
                        
                        set(obj.beg.rbt_1,'Value',1)
                        
                    case 'R'
                        
                        set(obj.beg.rbt_2,'Value',1)
                        
                    case 'S'
                        
                        set(obj.beg.rbt_3,'Value',1)
                        
                        set(obj.beg.txt1,'Enable','on')
                        set(obj.beg.edt1,'Enable','on')
                        set(obj.beg.edt1,'String',obj.behaviour_function)
                        
                end
                
            end
            
        end
        
        function rfg_closereq(obj,~,~)
           
            delete(obj.rfg.h)
            
            obj.rfg = [];
            
        end
        
        function beg_closereq(obj,~,~)
           
            delete(obj.beg.h)
            
            obj.beg = [];
            
        end
        
        function frg_closereq(obj,~,~)
           
            delete(obj.frg.h)
            
            obj.frg = [];
            
        end
        
        function rfg_edt_clb(obj,~,~)
            
            formula = get(obj.rfg.edt,'String');
            
            obj.timing_formula = formula;
            
        end
        
        function frg_edt_clb(obj,~,~)
            
            formula = get(obj.frg.edt,'String');
            
            obj.freq_formula = formula;
            
        end
        
        function beg_uibutgp_sel_chg_fcn(obj,source,eventdata)
            
            switch get(eventdata.NewValue,'String')
                
                case 'Constant'
                    
                    obj.behaviour = 'C';
                    
                    eval(['set(obj.parent_adwin.srf.but_',num2str(obj.rf_timing_nbr), ...
                        ',''String''              ,''',obj.behaviour,'''', ...
                        ');']);
                    
                    obj.behaviour_function = '';
                    set(obj.beg.txt1,'Enable','off')
                    set(obj.beg.edt1,'Enable','off')
                    set(obj.beg.edt1,'String','')
                    
                case 'Ramp'
                    
                    obj.behaviour = 'R';
                    
                    eval(['set(obj.parent_adwin.srf.but_',num2str(obj.rf_timing_nbr), ...
                        ',''String''              ,''',obj.behaviour,'''', ...
                        ');']);
                    
                    obj.behaviour_function = '';
                    set(obj.beg.txt1,'Enable','off')
                    set(obj.beg.edt1,'Enable','off')
                    set(obj.beg.edt1,'String','')
                    
                case 'Custom'
                    
                    obj.behaviour = 'S';
                    
                    eval(['set(obj.parent_adwin.srf.but_',num2str(obj.rf_timing_nbr), ...
                        ',''String''              ,''',obj.behaviour,'''', ...
                        ');']);
                    
                    set(obj.beg.txt1,'Enable','on')
                    set(obj.beg.edt1,'Enable','on')
                    
            end
            
        end
        
        function beg_edt1_clb(obj,~,~)
            
            obj.behaviour_function = get(obj.beg.edt1,'String');
            
        end
        
        function postset_timing_formula(obj,~,~)
            
           obj.timing = evalin('base',obj.timing_formula);
           
           if ~isempty(obj.rfg)&&ishandle(obj.rfg.h)
               
               set(obj.rfg.txt3,'String',num2str(obj.timing))
               
           end
           
           if ~isempty(obj.parent_adwin.srf)&&ishandle(obj.parent_adwin.srf.h)&&isfield(obj.parent_adwin.srf,['txt1_',num2str(obj.rf_timing_nbr)])
               
               eval(['set(obj.parent_adwin.srf.txt1_',num2str(obj.rf_timing_nbr),',''String'',''',obj.timing_formula,''')'])
               
           end
           
           if isequal(obj.rf_timing_nbr,length(obj.parent_adwin.rf_timings_array))&&~isequal(obj.timing,Inf)
               
               obj.parent_adwin.rf_timings_array(end+1) = Adwin.RFtiming;
               
               obj.parent_adwin.rf_timings_array(end).parent_adwin = obj.parent_adwin;
               
               obj.parent_adwin.rf_timings_array(end).rf_timing_nbr = length(obj.parent_adwin.rf_timings_array);
               
               obj.parent_adwin.rf_timings_array(end).timing_formula = 'Inf';
               
               obj.parent_adwin.rf_timings_array(end).freq_formula = '0';
               
               obj.parent_adwin.rf_timings_array(end).behaviour = 'C';

               temp = obj.parent_adwin.rf_timings_array(end);
               
               % New RF timing panel geometry
               
               c_start_ofs = 0.15;
               c_wth = 0.06;
               r_wth = 0.8;
               c_ofs = 0.0025;
               r_ofs = 0.1;
               
               eval(['obj.parent_adwin.srf.hsp1_',num2str(length(obj.parent_adwin.rf_timings_array)),' = uipanel(', ...
                   '''Parent''              ,obj.parent_adwin.srf.hsp1', ...
                   ',''BackgroundColor''    ,Adwin.Default_parameters.Panel_BackgroundColor', ...
                   ',''ForegroundColor''    ,Adwin.Default_parameters.Panel_ForegroundColor', ...
                   ',''HighlightColor''     ,Adwin.Default_parameters.Panel_HighlightColor', ...
                   ',''ShadowColor''        ,Adwin.Default_parameters.Panel_ShadowColor', ...
                   ',''FontName''           ,Adwin.Default_parameters.Panel_FontName', ...
                   ',''FontSize''           ,Adwin.Default_parameters.Panel_FontSize', ...
                   ',''FontUnits''          ,Adwin.Default_parameters.Panel_FontUnits', ...
                   ',''FontWeight''         ,Adwin.Default_parameters.Panel_FontWeight', ...
                   ',''SelectionHighlight'' ,Adwin.Default_parameters.Panel_SelectionHighlight', ...
                   ',''Units''              ,Adwin.Default_parameters.Panel_Units', ...
                   ',''Position''           ,[c_start_ofs+(length(obj.parent_adwin.rf_timings_array)-1)*(c_wth+c_ofs) r_ofs c_wth r_wth]', ...
                   ');']);
               
               % Analog outputs hsp3_i_j panels geometry
               
               c_wth = 0.595;
               r_wth = 0.495;
               c_ofs = 0.0025;
               r_ofs = 0.5025;
               
               eval(['obj.parent_adwin.srf.hsp1_',num2str(length(obj.parent_adwin.rf_timings_array)),'_1 = uipanel(', ...
                   '''Parent''              ,obj.parent_adwin.srf.hsp1_',num2str(length(obj.parent_adwin.rf_timings_array)), ...
                   ',''BackgroundColor''    ,Adwin.Default_parameters.Panel_BackgroundColor', ...
                   ',''ForegroundColor''    ,Adwin.Default_parameters.Panel_ForegroundColor', ...
                   ',''HighlightColor''     ,Adwin.Default_parameters.Panel_HighlightColor', ...
                   ',''ShadowColor''        ,Adwin.Default_parameters.Panel_ShadowColor', ...
                   ',''FontName''           ,Adwin.Default_parameters.Panel_FontName', ...
                   ',''FontSize''           ,Adwin.Default_parameters.Panel_FontSize', ...
                   ',''FontUnits''          ,Adwin.Default_parameters.Panel_FontUnits', ...
                   ',''FontWeight''         ,Adwin.Default_parameters.Panel_FontWeight', ...
                   ',''SelectionHighlight'' ,Adwin.Default_parameters.Panel_SelectionHighlight', ...
                   ',''Units''              ,Adwin.Default_parameters.Panel_Units', ...
                   ',''Position''           ,[c_ofs r_ofs c_wth r_wth]', ...
                   ');']);
               
               % RF Edit timings geometry
               
               c_wth = 0.95;
               r_wth = 0.8;
               c_ofs = 0.05;
               r_ofs = 0.05;
               
               eval(['obj.parent_adwin.srf.txt1_',num2str(length(obj.parent_adwin.rf_timings_array)),' = uicontrol(', ...
                   '''Parent''               ,obj.parent_adwin.srf.hsp1_',num2str(length(obj.parent_adwin.rf_timings_array)),'_1' ...
                   ',''Style''               ,''text''', ...
                   ',''String''              ,num2str(obj.parent_adwin.rf_timings_array(',num2str(length(obj.parent_adwin.rf_timings_array)),').timing)', ...
                   ',''Units''               ,Adwin.Default_parameters.Text_Units', ...
                   ',''Position''            ,[c_ofs r_ofs c_wth r_wth]',  ...
                   ',''ButtonDownFcn''       ,@temp.rf_timing_btd_fcn', ...
                   ',''Tag''                 ,','''tag_',num2str(length(obj.parent_adwin.rf_timings_array)),'''', ...
                   ');']);
               
               % RF but_j behaviour geometry
               
               c_wth = 0.395;
               r_wth = 0.495;
               c_ofs = 0.6025;
               r_ofs = 0.5025;
               
               eval(['obj.parent_adwin.srf.but_',num2str(length(obj.parent_adwin.rf_timings_array)),' = uicontrol(', ...
                   '''Parent''              ,obj.parent_adwin.srf.hsp1_',num2str(length(obj.parent_adwin.rf_timings_array)), ...
                   ',''Style''               ,''pushbutton''', ...
                   ',''String''              ,obj.parent_adwin.rf_timings_array(',num2str(length(obj.parent_adwin.rf_timings_array)),').behaviour', ...
                   ',''FontName''            ,Adwin.Default_parameters.Pushbutton_FontName', ...
                   ',''FontSize''            ,Adwin.Default_parameters.Pushbutton_FontSize', ...
                   ',''FontUnits''           ,Adwin.Default_parameters.Pushbutton_FontUnits', ...
                   ',''FontWeight''          ,Adwin.Default_parameters.Pushbutton_FontWeight', ...
                   ',''Units''               ,Adwin.Default_parameters.Pushbutton_Units', ...
                   ',''Position''           ,[c_ofs r_ofs c_wth r_wth]', ...
                   ',''Callback''           ,@temp.rf_beh_clb', ...
                   ',''Tag''                 ,','''tag_',num2str(length(obj.parent_adwin.rf_timings_array)),'''', ...
                   ');']);
               
               % Analog outputs hsp4_i_j panels geometry
               
               c_wth = 0.995;
               r_wth = 0.495;
               c_ofs = 0.0025;
               r_ofs = 0.0025;
               
               eval(['obj.parent_adwin.srf.hsp1_',num2str(length(obj.parent_adwin.rf_timings_array)),'_2 = uipanel(', ...
                   '''Parent''              ,obj.parent_adwin.srf.hsp1_',num2str(length(obj.parent_adwin.rf_timings_array)), ...
                   ',''BackgroundColor''    ,Adwin.Default_parameters.Panel_BackgroundColor', ...
                   ',''ForegroundColor''    ,Adwin.Default_parameters.Panel_ForegroundColor', ...
                   ',''HighlightColor''     ,Adwin.Default_parameters.Panel_HighlightColor', ...
                   ',''ShadowColor''        ,Adwin.Default_parameters.Panel_ShadowColor', ...
                   ',''FontName''           ,Adwin.Default_parameters.Panel_FontName', ...
                   ',''FontSize''           ,Adwin.Default_parameters.Panel_FontSize', ...
                   ',''FontUnits''          ,Adwin.Default_parameters.Panel_FontUnits', ...
                   ',''FontWeight''         ,Adwin.Default_parameters.Panel_FontWeight', ...
                   ',''SelectionHighlight'' ,Adwin.Default_parameters.Panel_SelectionHighlight', ...
                   ',''Units''              ,Adwin.Default_parameters.Panel_Units', ...
                   ',''Position''           ,[c_ofs r_ofs c_wth r_wth]', ...
                   ');']);
               
               % RF frequency geometry
               
               c_wth = 0.95;
               r_wth = 0.8;
               c_ofs = 0.05;
               r_ofs = 0.05;
               
               eval(['obj.parent_adwin.srf.txt2_',num2str(length(obj.parent_adwin.rf_timings_array)),' = uicontrol(', ...
                   '''Parent''               ,obj.parent_adwin.srf.hsp1_',num2str(length(obj.parent_adwin.rf_timings_array)),'_2' ...
                   ',''Style''               ,''text''', ...
                   ',''String''              ,num2str(obj.parent_adwin.rf_timings_array(',num2str(length(obj.parent_adwin.rf_timings_array)),').frequency)', ...
                   ',''Units''               ,Adwin.Default_parameters.Text_Units', ...
                   ',''Position''            ,[c_ofs r_ofs c_wth r_wth]',  ...
                   ',''ButtonDownFcn''       ,@temp.rf_frq_btd_fcn', ...
                   ',''Tag''                 ,','''tag_',num2str(length(obj.parent_adwin.rf_timings_array)),'''', ...
                   ');']);
               
           end

        end
        
        function postset_freq_formula(obj,~,~)
            
            obj.frequency = evalin('base',obj.freq_formula);
            
            if ~isempty(obj.frg)&&ishandle(obj.frg.h)
               
               set(obj.frg.txt3,'String',num2str(obj.frequency))
               
            end
           
            if ~isempty(obj.parent_adwin.srf)&&ishandle(obj.parent_adwin.srf.h)&&isfield(obj.parent_adwin.srf,['txt2_',num2str(obj.rf_timing_nbr)])
               
               eval(['set(obj.parent_adwin.srf.txt2_',num2str(obj.rf_timing_nbr),',''String'',''',obj.freq_formula,''')'])
               
           end
            
        end
        
        function postset_behaviour(obj,~,~)
            
            obj.parent_adwin.rf_seq_changed = 1;
            
            if ~isempty(obj.beg)&&ishandle(obj.beg.h)
               
               switch obj.behaviour
                    
                    case 'C'
                        
                        set(obj.beg.rbt_1,'Value',1)
                        
                    case 'R'
                        
                        set(obj.beg.rbt_2,'Value',1)
                        
                    case 'S'
                        
                        set(obj.beg.rbt_3,'Value',1)
                        
                        set(obj.beg.txt1,'Enable','on')
                        set(obj.beg.edt1,'Enable','on')
                        set(obj.beg.edt1,'String',obj.behaviour_function)
                        
                end
               
            end
            
            if ~isempty(obj.parent_adwin.srf)&&ishandle(obj.parent_adwin.srf.h)&&isfield(obj.parent_adwin.srf,['but_',num2str(obj.rf_timing_nbr)])
               
               eval(['set(obj.parent_adwin.srf.but_',num2str(obj.rf_timing_nbr),',''String'',''',obj.behaviour,''')'])
               
           end

        end
        
        function postset_behaviour_function(obj,~,~)
            
            obj.parent_adwin.rf_seq_changed = 1;
            
            if ~isempty(obj.beg)&&ishandle(obj.beg.h)
               
               set(obj.beg.edt1,'String',obj.behaviour_function)
               
            end
            
        end
        
        function preset_timing(obj,~,~)
            
            new_value = evalin('base',obj.timing_formula);
            
            if ~isequal(new_value,obj.timing)
               
                obj.parent_adwin.rf_seq_changed = 1;
                
            end
            
        end
        
        function preset_frequency(obj,~,~)
            
            new_value = evalin('base',obj.freq_formula);
            
            if ~isequal(new_value,obj.frequency)
               
                obj.parent_adwin.rf_seq_changed = 1;
                
            end
            
        end
        
    end
    
end

